use_frameworks!

platform :ios, '8.0'

target 'VHCycleVerticalView_Example' do
  pod 'VHCycleVerticalView', :path => '../'

  target 'VHCycleVerticalView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
